### ISSUE TITLE
Using with shadow-dom doesn't trigger onload function

### ISSUE THREAD

**Issue by knownasilya** [choojs/nanohtml#37]
``` js
import bel from 'bel';

export default class MyApp extends HTMLElement {
  createdCallback() {
    let greeting = this.getAttribute('greeting');
    let html = bel`
      <div>
        <div id="quotes">
          <div class="header" onload=${() => console.log('test')}>
            ${greeting ? greeting : 'Hello!'}
            <content select="my-name"></content>
          </div>
          <div class="body">
            <content select="my-profile"></content>
          </div>
        </div>
      </div>
    `;

    this.createShadowRoot().appendChild(html);
  }
}
```

Which I use:

``` html
<my-app greeting='Hi'>
  <my-name>Hello</my-name>
  <my-profile>
    This is my profile
  </my-profile>
</my-app>
```

The DOM renders fine, but on load there is nothing in the console.

**Comment by shama** [comment]
Hmm that is a tough one since `on-load` only watches the `document.body` and AFAIK can't observe mutations into shadow doms. We would need to observe the shadow root and there isn't an interface provided for that.

It would probably be expensive to detect whether an element is within a shadow dom, as we'd need to traverse the parentNode on render.

We might be able to have `on-load` watch for shadow doms added, then observe each of those as well. I have no idea if that would work or how expensive it would be though.

**Comment by knownasilya** [comment]
This is also an issue for other events, like `onclick`.

**Comment by shama** [comment]
@knownasilya That might be another issue, as other events are attached directly to the elements.

This works for me:

```js
var bel = require('bel')

var root = document.createElement('div')
var shadow = root.createShadowRoot()
document.body.appendChild(root)

var hello = bel`<button onclick=${function () {
  alert('works!')
}}>yo</button>`
shadow.appendChild(hello)
```

**Comment by knownasilya** [comment]
Weird, after trying it again, it works just fine for `onclick`.. at least that's not an issue.

**Comment by crapthings** [comment]
onload doesn't trigger properly when i switch route with choo

https://github.com/crapthings/webpack-choo-undefined

**Comment by goto-bus-stop** [comment]
this is no longer an issue with nanohtml because it doesn't include `on-load` anymore.
